import "./globals.css";
import { Inter } from "next/font/google";
import Navigation from "./components/Nav";
import Footer from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bobby Brown",
  description: "Generated by coihsan",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <main className="max-w-screen-lg mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
